In [9]:
import numpy as np
arr=np.arange(30,70,2)
arr.reshape((2,10))
print(arr.flatten())

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [20]:
ar=np.arange(2,10,2)
ari=np.arange(1,9,2)
print(np.concatenate([ar, ari], axis=0))
ar.reshape(2,2)
ari.reshape(2,2)
np.vstack((ar, ari))

[2 4 6 8 1 3 5 7]


array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [42]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)
for x in np.nditer(a):
  print(x,end=" ")

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
10 11 12 13 14 15 16 17 18 19 20 21 

In [44]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [45]:
arr2 = np.zeros((1,10), dtype='f')
arr2[0,6]='11'
print(arr2)


[[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]]


In [46]:
arr3 = np.arange(12,38)
arr4 = arr3[::-1]
print(arr4)


[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [40]:
arr5=[1,2,3,4]
arr6 = np.asfarray(arr5)
arr6

array([1., 2., 3., 4.])

In [52]:
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = '0'
print(arr8)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
arr9 = np.zeros((8,8), dtype='i')
arr9[1::2, ::2]=1
arr9[::2, 1::2]=1
print(arr9)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [63]:
mylist=[(1,2,3),(4,5,6)]
print(np.asarray(mylist))

[[1 2 3]
 [4 5 6]]


In [68]:
a=[10,20,30]
b=[40,50,60]
a= np.append(a,b)
print(a)

[10 20 30 40 50 60]


In [79]:
a1=[0,10,20,40,60]
a2=[0,40]
print(np.in1d(a1,a2))

[ True False False  True False]


In [81]:
print(np.intersect1d(a1,a2))

[ 0 40]


In [85]:
x=np.array([[1,1],[2,3]])
print(np.unique(x))

[1 2 3]
